version: "3"
services:
  postgres:
    image: postgres:10.3
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SECRET_POSTGRES_PASSWORD: password
      POSTGRES_DB: models_dev
  postgres-test:
    image: postgres:10.3
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      SECRET_POSTGRES_PASSWORD: password
      POSTGRES_DB: models_test
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:4.1.2
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

